// constants.js
export const navLinks = [
  "Home",
  {
    title: "Services",
    dropdown: [
      { text: "Report", 
      href: "/",
      subdropdown: [
          { text: "Routine Report", href: "/" },
          { text: "Periodic Report", href: "/" },
          { text: "Informal Report", href: "/" },
          { text: "Formal Report", href: "/" },
          { text: "CDR Report", href: "/" },
          { text: "Analytical Report", href: "/" },
          { text: "Proposal Report", href: "/" },
          { text: "Technical Report", href: "/" },
          { text: "Informational Report", href: "/" },
          { text: "Internal and external Report", href: "/" },
          { text: "Vertical and Lateral Report", href: "/" },
      ]
   },
      { text: "Coursework", href: "/",
      subdropdown: [
          { text: "Coursework Writing Help", href: "/" },
          { text: "Java Coursework", href: "/" },
          { text: "Accounting Coursework", href: "/" },
          { text: "Business Coursework", href: "/" },
          { text: "Finance Coursework", href: "/" },
          { text: "Marketing Coursework", href: "/" },
          { text: "English Coursework", href: "/" },
          { text: "Science Coursework", href: "/" },
          { text: "Chemistry Coursework", href: "/" },
          { text: "Law Coursework", href: "/" },
          { text: "Economics Coursework", href: "/" },
          { text: "College Coursework", href: "/" },
          { text: "Biology Coursework", href: "/" },
          { text: "Psychology Coursework", href: "/" },
          { text: "University Coursework", href: "/" },
          { text: "Maths Coursework", href: "/" },
      ]
  },
      { text: "Essay", href: "/service2",
      subdropdown: [
          { text: "Essay Writing Help", href: "/" },
      ] },
      { text: "Case Study", href: "/",
      subdropdown: [
          { text: "Case Study Writing Help", href: "/" },
          { text: "Do My Case Study", href: "/" },
          { text: "Write My Case Study", href: "/" },
          { text: "Buy Case Study", href: "/" },
          { text: "Management Case Study", href: "/" },
          { text: "Business Case Study", href: "/" },
          { text: "Accounting Case Study", href: "/" },
          { text: "Marketing Case Study", href: "/" },
          { text: "Finance Case Study", href: "/" },
          { text: "Economics Case Study", href: "/" },
          { text: "Law Case Study", href: "/" },
          { text: "Medical Case Study", href: "/" },
          { text: "Engineering Case Study", href: "/" },
          { text: "Biology Case Study", href: "/" },
          { text: "Chemistry Case Study", href: "/" },
          { text: "Nursing Case Study", href: "/" },
          ]},
      { text: "Assignment", href: "/",
     subdropdown: [
      { text: "Assignment Writing Help", href: "/" },
      { text: "MBA Assignment", href: "/" },
      { text: "HND Assignment", href: "/" },
      { text: "Cookery Assignment", href: "/" },
      { text: "Management Assignment Help", href: "/",
    subsubdropdown: [
      { text: "Operations Management", href: "/" },
      { text: "Leadership Management", href: "/" },
      { text: "Customer Relationship Management", href: "/" },
      { text: "Business Management", href: "/" },
      { text: "Business Environment", href: "/" },
      { text: "Business Development", href: "/" },
      { text: "Business Analysis", href: "/" },
      { text: "Business Intelligence", href: "/" },
      { text: "Business Plan", href: "/" },
      { text: "Business Statistics", href: "/" },
      { text: "IT Management", href: "/" },
      { text: "Project Management", href: "/" },
      { text: "Marketing Management", href: "/" },
      { text: "Brand Management", href: "/" },
      { text: "Behavior Management", href: "/" },
      { text: "Consumer Behavior", href: "/" },
    ]},
     ]},
      { text: "Dissertation", href: "/",
    subdropdown: [
      { text: "Dissertation Writing Help", href: "/"}
    ] },
      { text: "Plagiarism Checker", href: "/" },
      { text: "Proofreading and Editing", href: "/" },
      { text: "Referencing", href: "/" },
      { text: "Research Paper", href: "/", subdropdown:[
      { text: "Analytical Research Paper", href: "/" },
      { text: "Argumentative Research Paper", href: "/" },
      { text: "Cause and Effect Research Paper", href: "/" },
      { text: "Experimental Research Paper", href: "/" },
      { text: "Problem Solution Research Paper", href: "/" },
      { text: "Survey Research Paper", href: "/" },
      ] },
      { text: "Term Paper", href: "/" },
      { text: "Transcription Services", href: "/" },
    ]
  },
  {
    title: "Countries",
    dropdown: [
      { text: "Service 1", 
      href: "/service1"},
      { text: "Service 2", href: "/service2" },
      { text: "NewZealand", href: "/service2" },
      { text: "Transcription service", href: "/service2" },
      { text: "Service Raassf", href: "/service2" },
      { text: "Plagiarism Checker", href: "/service2" },
      { text: "Term Paper", href: "/service2" },
      { text: "Service 2", href: "/service2" },
      { text: "Service 2", href: "/service2" },
    ]
  },
  "Contact",
  "About",
];